# Generated by Django 4.0.3 on 2022-03-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('address_one', models.CharField(max_length=254)),
                ('address_two', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('json_order', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
